import { expect, test } from '@playwright/test';

test.describe('Copy to clipboard feature', () => {
	test.beforeEach(async ({ context, browserName }) => {
		// Grant clipboard permissions for testing, but only for browsers that support it
		if (browserName !== 'webkit') {
			await context.grantPermissions(['clipboard-read', 'clipboard-write']);
		}
	});

	test('should copy output to clipboard when copy button is clicked', async ({
		page,
		browserName
	}) => {
		await page.goto('/');
		const outputTestDiv = page.locator('#csv-output');
		const copyButton = page.locator('button.copy-btn');

		// Wait for the app to be fully initialized. A good signal for this is when
		// the output is not blank. This is more robust than waiting
		// for a single element to be enabled and ensures the initial data is loaded.
		await expect(outputTestDiv).not.toBeEmpty();

		// grab the content to ensure our next action actually changes it.
		const initialContent = await outputTestDiv.textContent();

		// Interact with the page to generate a different output.
		// The <input> is hidden for styling, so we click the visible text
		// inside the <label> to toggle the checkbox state, just like a user would.
		await page.getByText('Mon').click();
		await page.getByText('Tue').click();

		// Wait for the output to be regenerated by checking that the output value has changed.
		await expect(outputTestDiv).not.toHaveText(initialContent as string);
		await expect(copyButton).toBeEnabled();

		// Get the new content that should be copied.
		const newContent = await outputTestDiv.textContent();

		// Ensure there is actually new content to copy.
		expect(newContent).not.toBe(initialContent);

		// Click the copy button.
		await copyButton.click();

		// Verify the clipboard content matches the new content exactly.
		if (browserName !== 'webkit') {
			const clipboardText = await page.evaluate(() => navigator.clipboard.readText());
			expect(clipboardText).toBe(newContent);
		}
	});

	test('should display a "Copied!" toast message on successful copy', async ({ page }) => {
		await page.goto('/');
		const copyButton = page.locator('button.copy-btn');
		await expect(page.locator('#csv-output')).not.toHaveText('Loading data...');
		await copyButton.click();
		await page.waitForSelector('.toast-message');

		const toast = page.locator('.toast-message');
		await expect(toast).toBeVisible();
		await expect(toast).toHaveText('Copied!');
		await expect(toast).toBeHidden();
	});

	test('should copy HTML to clipboard when alt-clicking the copy button', async ({
		page,
		browserName
	}) => {
		await page.goto('/');
		const copyButton = page.locator('#copy_button');
		await expect(page.locator('#csv-output')).not.toHaveText('Loading data...');

		await copyButton.click({ modifiers: ['Alt'] });

		if (browserName !== 'webkit') {
			const clipboardContent = await page.evaluate(async () => {
				const clipboardItems = await navigator.clipboard.read();
				for (const item of clipboardItems) {
					if (item.types.includes('text/html')) {
						const blob = await item.getType('text/html');
						return await blob.text();
					}
				}
				return '';
			});
			expect(clipboardContent).toMatch(/^<table/);
		}

		const toast = page.locator('.toast-message');
		await expect(toast).toBeVisible();
		await expect(toast).toHaveText('Copied with formatting!');
		await expect(toast).toBeHidden();
	});
});
