import { expect, test } from '@playwright/test';

test.describe('Schedule copy to clipboard', () => {
	test.beforeEach(async ({ context, browserName }) => {
		// Grant clipboard permissions for testing, but only for browsers that support it.
		if (browserName !== 'webkit') {
			await context.grantPermissions(['clipboard-read', 'clipboard-write']);
		}
	});

	test('should copy the rendered output to the real clipboard', async ({ page, browserName }) => {
		await page.goto('/');
		const outputDiv = page.locator('#csv-output');
		const copyButton = page.locator('#copy_button');

		// Wait for the app to be fully initialized. A good signal is when the output
		// is not blank and no longer loading. This is more robust than waiting for a
		// single element to be enabled and ensures the initial data is loaded.
		await expect(outputDiv).not.toBeEmpty();
		await expect(outputDiv).not.toHaveText('Loading data...');

		// Grab the content to ensure our next action actually changes it.
		const initialContent = await outputDiv.textContent();

		// Interact with the page to generate a different output.
		// The <input> is hidden for styling, so we click the visible text inside the
		// <label> to toggle the checkbox state, just like a user would.
		await page.getByText('Mon', { exact: true }).click();
		await page.getByText('Tue', { exact: true }).click();

		// Wait for the output to be regenerated by checking the output has changed.
		await expect(outputDiv).not.toHaveText(initialContent as string);
		await expect(copyButton).toBeEnabled();

		// The new content is the single source of truth for what should be copied.
		const newContent = await outputDiv.textContent();
		expect(newContent).toBeTruthy();
		expect(newContent).not.toBe(initialContent);

		// Click the copy button.
		await copyButton.click();

		// Verify the real clipboard matches the rendered output exactly. Poll because
		// the write is async and the click handler does not await it.
		if (browserName !== 'webkit') {
			await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(newContent);
		}

		// Alt-click copies the rendered table (with formatting) via execCommand('copy').
		await copyButton.click({ modifiers: ['Alt'] });

		if (browserName !== 'webkit') {
			await expect
				.poll(() =>
					page.evaluate(async () => {
						const clipboardItems = await navigator.clipboard.read();
						for (const item of clipboardItems) {
							if (item.types.includes('text/html')) {
								const blob = await item.getType('text/html');
								return await blob.text();
							}
						}
						return '';
					})
				)
				.toMatch(/^<table/);
		}

		const toast = page.locator('.toast-message');
		await expect(toast).toBeVisible();
		await expect(toast).toHaveText('Copied with formatting!');
		await expect(toast).toBeHidden();
	});
});
